['Home'=>[  'EN'=>'Home',
            'TM'=>'Baş sahypa',
            'RU'=>'Главная '],
'About'=>[  'EN'=>'About',
            'TM'=>'Biz barada',
            'RU'=>'О нас '],
'Contacts'=>[   'EN'=>'Contacts',
            'TM'=>'Habarlaşmak',
            'RU'=>'Контакты '],
'Sign Up'=>[    'EN'=>'Sign Up',
            'TM'=>'Registrasiýa',
            'RU'=>'Регистрация'],
'Login In'=>[   'EN'=>'Login In',
            'TM'=>'Girmek',
            'RU'=>'Вход'],
'Get Started'=>[    'EN'=>'Get Started',
            'TM'=>'Başla',
            'RU'=>'Начать']]