<?php 
     return[
        'css'=>[
            'source/general/css/header.css',
            'source/main/css/style.css',
            'source/main/css/main-side.css',
            'source/general/icons/icons/all.css'
        ],
        'js'=>[
            "source/general/js/jquery/jquery-3.4.1.min.js",
            //"source/general/js/header.js",
            'source/main/js/script.js',
            "source/general/js/gsap/gsap.min.js",
            //'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js',
            'source/main/js/animation.js',
            'source/main/js/card.js',
            'source/main/js/notification.js'
        ]
    ];
?>