<?php 
     return[
        'css'=>[
            "source/general/icons/icons/all.css",
            'source/general/css/header.css',
            'source/profile/css/style.css',
            'source/profile/css/profile.css',
        ],
        'js'=>[
            'source/general/js/jquery/jquery-3.4.1.min.js',
            "source/general/js/header.js",
            "source/profile/js/main.js",
            "source/profile/js/functions.js",
            "source/profile/js/password.js"
        ]
    ];
?>