<?php 
     return[
        'css'=>[
            "source/signup/build/css/demo.css",
            "source/signup/build/css/intlTelInput.css",
            "source/signup/css/style.css",
            "source/signup/icon/icons/all.css"
        ],
        'js'=>[
            "source/general/js/jquery/jquery-3.4.1.min.js",
            "source/general/validator/validator.min.js",
            "source/signup/build/js/intlTelInput.js",
            "source/signup/build/js/utils.js",
            "source/signup/js/script.js"
        ]
    ];
?>